Template sweep -- fix bugs in Vue and Lit
holochain/scaffolding pull request #130
Opened 2023-10-03 22:20 UTC by pdaoust

I don't claim this is a thorough sweep that catches all bugs, but it does catch all bugs discovered via following the Getting Started Guide but choosing Lit and Vue instead of Svelte for the templating engine.

2023-11-02 15:18 UTC, ThetaSinner commented
@pdaoust Same with this one, please can it target `main`? Then would you be willing to go through and comment on the PR with a description of what is being changed/fixed so I can do some testing?

I'm happy reviewing the code but I don't know the repo well enough to understand what's changing without having a conversation about it if that's okay! :)

2023-11-03 16:53 UTC, ThetaSinner commented
This is now ready for review and can be merged when ready

2024-01-17 20:59 UTC, c12i requested changes
Discovered similar bugs, at least for the `Vue` and `Svelte` templates hence why I am returning to this PR, I think we should be getting this PR merged as it fixes some critical bugs

@pdaoust kindly let me know if you are in a position to resolve the merge conflicts

2024-01-17 20:59 UTC, c12i commented on src/scaffold/entry_type.rs
> +        .collect();
A little more cleaner 🙂

```suggestion
    let widget_fields = fields
        .iter()
        .cloned()
        .filter(|f| f.widget.is_some())
        .collect();
```

2024-01-17 23:05 UTC, c12i commented on src/scaffold/entry_type.rs
> +        .collect();
Taking back this comment, perhaps we won't need this fix if the changes #128 are approved

2024-09-25 10:57 UTC, c12i commented
@pdaoust, allow me to close this PR since it is stale at the moment and most of the changes made here have long been addressed

2024-10-01 17:27 UTC, pdaoust commented
Sure @c12i . Are there any fixes that haven't already been made? Should I do a new PR with those?

2024-10-01 17:27 UTC, closed without merging

2024-10-02 07:21 UTC, c12i commented
Thanks @pdaoust, I don't think there are any changes at the moment, I inadvertently addressed them while transitioning the templates to the new styling.