Add holo-dev-server to the dev shell when --holo is passed
holochain/scaffolding pull request #181
Opened 2024-01-15 16:02 UTC by r-vdp

We add a --holo flag to the example subcommand.
When this flag is passed, we add holo-nixpkgs as a flake input and we add holo-dev-server to the dev shell's packages.

2024-01-15 20:35 UTC, r-vdp commented
@c12i I pushed a commit to hopefully fix the tests. Weird though that github does not show any log output for the failed runs.

2024-01-16 08:06 UTC, c12i requested changes

2024-01-16 08:06 UTC, c12i commented on run_test.sh
> +  echo 'holo-dev-server is available in the PATH while it shouldn\'t'
The apostrophe doesn't appear to be correctly escaped, might be what's causing CI to fail

```suggestion
  echo 'holo-dev-server is available in the PATH while it shouldn'\''t'
```

2024-01-16 08:08 UTC, c12i commented
> @c12i I pushed a commit to hopefully fix the tests. Weird though that github does not show any log output for the failed runs.

I noticed this too, not sure why this is the case. However, I ran the tests locally (with above fixes), and the script exits with this error

```sh
holo-dev-server is NOT available in the PATH
```

2024-01-16 09:08 UTC, r-vdp commented
> > @c12i I pushed a commit to hopefully fix the tests. Weird though that github does not show any log output for the failed runs.
> 
> I noticed this too, not sure why this is the case. However, I ran the tests locally (with above fixes), and the script exits with this error
> 
> ```shell
> holo-dev-server is NOT available in the PATH
> ```

They were definitely working locally for me. I'll look into it.

2024-01-18 13:09 UTC, c12i commented
@r-vdp the tests are still failing after your fix, could you kindly have a look? I would like to support, but I'm unfortunately still new to nix, feel free to follow up with the rest of the team on mattermost for assistance with this if it continues to persist

2024-01-18 16:13 UTC, r-vdp commented
Hi @c12i. Well, I know why we get the error, but we are still discussing with some other team members about the most desirable manner of fixing it, since there are some trade-offs to take into account.
So I'm waiting for us to take a final decision before continuing on this PR because there's also the possibility that we'll take another approach.

I will mark the PR as draft for now until we've figured out how we want to continue.

2024-03-21 01:04 UTC, r-vdp commented
@c12i we finally got all the required pieces in place at the holo side. Would you be able to give this another look?

2024-03-21 01:05 UTC, r-vdp commented
Please review the commits separately, as the first two commits are just the result of running standard formatters to avoid reformatting later on.

2024-03-21 10:53 UTC, c12i approved these changes
LGTM, should probably remove it from draft mode, right @r-vdp?

2024-03-21 10:53 UTC, c12i commented on src/cli.rs
> +                holo_enabled,
Thanks for adding this change

2024-03-21 11:18 UTC, r-vdp commented
@c12i I undrafted and pushed a small change to remove a line from the diff that was not needed anymore.

2024-03-21 16:04 UTC, merged