Use hc-spin cli
holochain/scaffolding pull request #200
Opened 2024-01-29 12:26 UTC by matthme

This PR switches to using the hc-spin CLI instead of `hc launch` by default since it provides better developer tools.
It keeps the option to run the happ in tauri explicitly via `npm run start:tauri` if that's desired.

2024-01-29 13:35 UTC, ThetaSinner commented
The back-port probably will go via a PR but in a batch with other changes, and yes develop is still at 0.2. That going to 0.3 is waiting on tryorama I think

2024-01-29 13:37 UTC, c12i commented
> That going to 0.3 is waiting on tryorama I think

`tryorama` is actually now updated to a `0.3` compatible version, `hc launch` is the only issue left. I testing `hc-spin` with `0.3` would be something I start testing out next after this gets merged

2024-01-29 13:38 UTC, matthme commented
> The back-port probably will go via a PR but in a batch with other changes

Okay. Just note that it's not a 1:1 backport to 0.1 since it will require a different version of hc-spin (`^0.100.1`) as there are differences in hc sandbox between holochain 0.1 and 0.2.

2024-01-29 22:47 UTC, matthme commented
Made another PR (#201) now targeting develop. Will leave this one open for now since there are some differences between holochain 0.1 and holochain 0.2 but feel free to close if deemed unnecessary.

2024-01-30 06:24 UTC, c12i requested changes

2024-01-30 06:24 UTC, c12i commented on templates/lit/web-app/package.json.hbs
> +    "start:tauri": "AGENTS=2 npm run network",
```suggestion
    "start:tauri": "AGENTS=2 npm run network:tauri",
```

2024-01-30 06:24 UTC, c12i commented on templates/svelte/web-app/package.json.hbs
> +    "start:tauri": "AGENTS=2 npm run network",
```suggestion
    "start:tauri": "AGENTS=2 npm run network:tauri",
```

2024-01-30 06:24 UTC, c12i commented on templates/vanilla/web-app/package.json.hbs
> +    "start:tauri": "AGENTS=2 npm run network",
```suggestion
    "start:tauri": "AGENTS=2 npm run network:tauri",
```

2024-01-30 06:24 UTC, c12i commented on templates/vue/web-app/package.json.hbs
> +    "start:tauri": "AGENTS=2 npm run network",
```suggestion
    "start:tauri": "AGENTS=2 npm run network:tauri",
```

2024-01-30 10:05 UTC, matthme commented on templates/lit/web-app/package.json.hbs
> +    "start:tauri": "AGENTS=2 npm run network",
fixed, thank you!

2024-01-30 21:57 UTC, c12i approved these changes

2024-02-06 15:52 UTC, merged