Adds holochain_client_version variable to example package.json
holochain/scaffolding pull request #207
Opened 2024-02-07 10:27 UTC by matthme

I haven't actually tested it yet but I'm assuming the example package.json.hbs has access to the `holochain_client_version` variable as well.

2024-02-07 10:39 UTC, c12i commented
@matthme  unfortunately not, this is the only data passed to the example templates at  https://github.com/holochain/scaffolding/blob/develop/src/templates/example.rs#L24

I do think it makes sense to reference from the `versions.rs` rather than have them hard coded, it becomes very easy to miss updating these hard-coded values

```rs
 let data = ScaffoldExampleData {
        example: example.to_string(),
 };
```

2024-02-07 10:41 UTC, matthme commented
Oh I see...yes I agree. It's really easy to miss them (as happened in this case).

2024-02-08 14:09 UTC, c12i requested changes

2024-02-08 14:09 UTC, c12i commented on templates/vanilla/example/ui/package.json.hbs
> +      "@holochain/client": "{{holochain_client_version}}",
Prefer the hardcoded version for now

will create a PR to expose these values to the example templats

2024-02-19 15:42 UTC, c12i commented
Closing in favour of #218

2024-02-19 15:42 UTC, closed without merging