fix: Ensure is holo env var is passed at build time
holochain/scaffolding pull request #251
Opened 2024-04-05 13:29 UTC by c12i

2024-04-05 19:52 UTC, matthme approved these changes
I have no context about this env var because I'm not familiar with the Holo side of things but from what I can judge the change looks fine.

2024-04-08 23:04 UTC, robbiecarlton requested changes
@c12i I think I'd like to do this a different way: if you instead having a separate `build:holo` script here that is only included if `{{holo_enabled}}` is true you get two benefits

1) you still have the non holo build script for use with the parent script that builds a webhapp. Holo doesn't use the webhapp format, but we anticipate there will be happs that need both a webhapp (non holo) release and separately a holo UI, so this would cover both cases

2) `VITE_APP_IS_HOLO` doesn't mean anything in the ui if `{{holo_enabled}}` is false, so it's going to be confusing for people to see `VITE_APP_IS_HOLO=false` in their scripts when they didn't pass the `--holo` flag in, and potentially don't know anything about holo

2024-04-09 16:39 UTC, c12i commented on templates/lit/web-app/ui/package.json.hbs
> +    "build": "{{#if holo_enabled}}VITE_APP_IS_HOLO=true {{/if}}vite build",
I see, this would also mean having a separate `package:holo` to target this separate `build:holo` script then

2024-04-09 21:45 UTC, robbiecarlton approved these changes
Approved. I think there's one addition that you don't need, but don't want to block you any longer, if you remove it, it will make thinks simpler for happ devs, but rn they have all the functionality they need

2024-04-09 21:45 UTC, robbiecarlton commented on templates/custom-template/custom-template/template/web-app/package.json.hbs
> +    "package:holo": "npm run build:happ && npm run package:holo -w ui && hc web-app pack workdirk --recursive",
I don't think you need this one, because we don't ever need a webhapp file for holo

2024-04-10 09:56 UTC, merged